name: "Java CI"

on:
  push:
  pull_request:

jobs:
  test:
    name: "Java: Tests"
    # includes all needed software needed for tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone commit
        run: |
          git init
          git remote add origin https://github.com/${{ github.repository }}.git
          git fetch --depth=1 origin ${{ github.sha }} --progress
          git checkout FETCH_HEAD

      - name: Configure pre-installed Java 25
        run: |
          echo "JAVA_HOME=$JAVA_HOME_25_X64" >> $GITHUB_ENV
          echo "$JAVA_HOME_25_X64/bin" >> $GITHUB_PATH

      - name: Check Java version
        run: |
          java -version
          javac -version

      - name: Compile main project code
        run: /bin/time -v make compile verbose=true

      - name: Compile tests
        run: /bin/time -v make test-compile verbose=true

      - name: Execute tests
        run: /bin/time -v make test-execute verbose=true
